<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-V8Q69O7J" failures="3" tests="4" name="Test1" time="16.236" errors="0" timestamp="2023-01-06T10:24:45 IST">
  <testcase classname="com.DataproviderClass.Acti_Time_Login_Page0" name="LoginCredential1" time="2.78"/>
  <testcase classname="com.DataproviderClass.Acti_Time_Login_Page0" name="LoginCredential2" time="0.482">
    <failure type="java.lang.AssertionError" message=" URL is not matched  expected [http://localhost:90/user/submit_tt.do] but found [http://localhost:90/login.do]">
      <![CDATA[java.lang.AssertionError:  URL is not matched  expected [http://localhost:90/user/submit_tt.do] but found [http://localhost:90/login.do]
at com.DataproviderClass.Acti_Time_Login_Page0.LoginCredential2(Acti_Time_Login_Page0.java:57)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- LoginCredential2 -->
  <testcase classname="com.DataproviderClass.Acti_Time_Login_Page0" name="LoginCredential3" time="0.456">
    <failure type="java.lang.AssertionError" message=" URL is not matched  expected [http://localhost:90/user/submit_tt.do] but found [http://localhost:90/login.do]">
      <![CDATA[java.lang.AssertionError:  URL is not matched  expected [http://localhost:90/user/submit_tt.do] but found [http://localhost:90/login.do]
at com.DataproviderClass.Acti_Time_Login_Page0.LoginCredential3(Acti_Time_Login_Page0.java:75)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- LoginCredential3 -->
  <testcase classname="com.DataproviderClass.Acti_Time_Login_Page0" name="LoginCredential4" time="0.463">
    <failure type="java.lang.AssertionError" message=" URL is not matched  expected [http://localhost:90/user/submit_tt.do] but found [http://localhost:90/login.do]">
      <![CDATA[java.lang.AssertionError:  URL is not matched  expected [http://localhost:90/user/submit_tt.do] but found [http://localhost:90/login.do]
at com.DataproviderClass.Acti_Time_Login_Page0.LoginCredential4(Acti_Time_Login_Page0.java:93)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- LoginCredential4 -->
</testsuite> <!-- Test1 -->
