<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-V8Q69O7J" failures="1" tests="2" name="com.DataproviderClass.Acti_Time_Login_Page1" time="11.612" errors="0" timestamp="2023-01-06T10:53:54 IST" skipped="0">
  <testcase classname="com.DataproviderClass.Acti_Time_Login_Page1" name="LoginCredential1" time="7.111"/>
  <system-out/>
  <testcase classname="com.DataproviderClass.Acti_Time_Login_Page1" name="LoginCredential2" time="4.501">
    <failure message=" URL is not matched  expected [http://localhost:90/user/submit_tt.do] but found [http://localhost:90/login.do]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError:  URL is not matched  expected [http://localhost:90/user/submit_tt.do] but found [http://localhost:90/login.do]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at com.DataproviderClass.Acti_Time_Login_Page1.LoginCredential2(Acti_Time_Login_Page1.java:57)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
at java.base/java.lang.reflect.Method.invoke(Method.java:577)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:962)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
    </failure>
  </testcase> <!-- LoginCredential2 -->
  <system-out/>
</testsuite> <!-- com.DataproviderClass.Acti_Time_Login_Page1 -->
